import AppKit.NSPasteboard
import Defaults

extension NSPasteboard.PasteboardType: Defaults.Serializable {
  /// HEIC image pasteboard type.
  static let heic = NSPasteboard.PasteboardType(rawValue: "public.heic")
  /// JPEG image pasteboard type.
  static let jpeg = NSPasteboard.PasteboardType(rawValue: "public.jpeg")
  /// Universal clipboard type set by Handoff / continuity.
  static let universalClipboard = NSPasteboard.PasteboardType(rawValue: "com.apple.is-remote-clipboard")

  /// Standard type flagging content as auto-generated by a clipboard manager (see nspasteboard.org).
  static let autoGenerated = NSPasteboard.PasteboardType(rawValue: "org.nspasteboard.AutoGeneratedType")
  /// Standard type flagging content as concealed (e.g. password managers; see nspasteboard.org).
  static let concealed = NSPasteboard.PasteboardType(rawValue: "org.nspasteboard.ConcealedType")
  /// Standard type carrying the originating app/source (see nspasteboard.org).
  static let source = NSPasteboard.PasteboardType(rawValue: "org.nspasteboard.source")
  /// Standard type flagging transient content not worth persisting (see nspasteboard.org).
  static let transient = NSPasteboard.PasteboardType(rawValue: "org.nspasteboard.TransientType")

  /// Flag indicating the copy was modified by a clipboard tool (Maccy issue #429).
  static let modified = NSPasteboard.PasteboardType(rawValue: "x.nspasteboard.ModifiedType")

  /// Marks that the copy originated from Maccy itself.
  static let fromMaccy = NSPasteboard.PasteboardType(rawValue: "org.p0deje.Maccy")

  /// Microsoft Word ObjectLink bookmark (link) type.
  static let microsoftObjectLink = NSPasteboard.PasteboardType(rawValue: "com.microsoft.ObjectLink")
  /// Microsoft Word Link-Source bookmark type.
  static let microsoftLinkSource = NSPasteboard.PasteboardType(rawValue: "com.microsoft.Link-Source")

  /// Safari LinkPresentation preview metadata, which changes frequently per copy.
  static let linkPresentationMetadata = NSPasteboard.PasteboardType(rawValue: "com.apple.linkpresentation.metadata")
  // Safari custom WebKit pasteboard data, which changes frequently per copy.
  // swiftlint:disable:next line_length
  static let customWebKitPasteboardData = NSPasteboard.PasteboardType(rawValue: "com.apple.WebKit.custom-pasteboard-data")

  /// Chromium (VS Code) custom web data.
  static let customChromiumWebData = NSPasteboard.PasteboardType(rawValue: "org.chromium.web-custom-data")
  /// Chromium (VS Code) source URL.
  static let chromiumSourceUrl = NSPasteboard.PasteboardType(rawValue: "org.chromium.source-url")
  /// Chromium (VS Code) internal render-frame-host token.
  static let chromiumSourceToken = NSPasteboard.PasteboardType(rawValue: "org.chromium.internal.source-rfh-token")

  /// Apple Notes rich-text pasteboard type.
  static let notesRichText = NSPasteboard.PasteboardType(rawValue: "com.apple.notes.richtext")
}
