// swiftlint:disable file_length
import XCTest
@testable import Maccy

// Pure, DB-free, NSPasteboard-free tests for `filterContents(_:application:config:)`.
//
// Every test builds synthetic `ContentDTO` values and an `IngestConfig` snapshot,
// then asserts that `filterContents` replicates the rules in `Clipboard.contents(from:)`
// (Clipboard.swift ~227-247), `filteredTypes` (~251-265), `shouldIgnore(types)`
// (~267-273), `shouldIgnore(item)` regex (~283-310), `isEmptyString` (~312-322) and
// `richText(_:)` (~324-344). No `NSPasteboard`, no SwiftData, no actor is touched.
class IngestFilterTests: XCTestCase { // swiftlint:disable:this type_body_length
  // Standard pasteboard type rawValues (UTIs). See NSPasteboard.PasteboardType.
  private let stringType = "public.utf8-plain-text"
  private let rtfType = "public.rtf"
  private let htmlType = "public.html"
  private let pngType = "public.png"
  private let tiffType = "public.tiff"
  private let jpegType = "public.jpeg"
  private let heicType = "public.heic"
  private let fileURLType = "public.file-url"
  private let transientType = "org.nspasteboard.TransientType"
  private let autoGeneratedType = "org.nspasteboard.AutoGeneratedType"
  private let concealedType = "org.nspasteboard.ConcealedType"

  private let microsoftLinkSource = "com.microsoft.Link-Source"
  private let microsoftObjectLink = "com.microsoft.ObjectLink"
  private let pdfType = "com.adobe.pdf"

  /// The full supported set, mirroring `Clipboard.supportedTypes`.
  private var allSupportedTypes: Set<String> {
    [
      fileURLType, heicType, htmlType, jpegType, pngType, rtfType, stringType, tiffType
    ]
  }

  /// A baseline config with everything enabled and no ignore rules. Tests override
  /// only the fields relevant to each assertion.
  private var defaultConfig: IngestConfig {
    IngestConfig(
      supportedTypes: allSupportedTypes,
      enabledTypes: allSupportedTypes,
      ignoredTypes: [transientType, autoGeneratedType, concealedType],
      maxValueSize: 10 * 1_024 * 1_024,
      richTextParsingLimit: 512 * 1_024,
      regularExpressionInputLimit: 2_000,
      ignoreRegexp: [],
      ignoredApps: [],
      ignoreAllAppsExceptListed: false,
      titlePreviewLimit: 1_000
    )
  }

  private func dto(_ type: String, _ value: String) -> ContentDTO {
    let data = value.data(using: .utf8)
    return ContentDTO(type: type, value: data, fingerprint: nil, size: data?.count ?? 0)
  }

  private func dto(_ type: String, _ data: Data) -> ContentDTO {
    ContentDTO(type: type, value: data, fingerprint: nil, size: data.count)
  }

  // MARK: - Survival

  func testPlainTextSurvives() {
    let result = filterContents([dto(stringType, "hello")], application: nil, config: defaultConfig)

    XCTAssertEqual(result.map(\.type), [stringType])
    XCTAssertEqual(result.first?.value, "hello".data(using: .utf8))
  }

  func testMultipleTypesSurviveWhenAllEnabled() {
    let result = filterContents(
      [dto(stringType, "hi"), dto(pngType, Data([0x89, 0x50]))],
      application: nil,
      config: defaultConfig
    )

    XCTAssertEqual(Set(result.map(\.type)), Set([stringType, pngType]))
  }

  // MARK: - shouldIgnore(types) parity (~267-273)

  func testTypeNotInEnabledTypesIsFilteredOut() {
    // Only png enabled; a string content should be dropped entirely because the
    // global type set becomes disjoint from enabledTypes after filtering the string
    // — replicating `shouldIgnore(types)` returning true when the remaining type set
    // is disjoint from enabledTypes.
    var config = defaultConfig
    config.enabledTypes = [pngType]

    let result = filterContents([dto(stringType, "hi")], application: nil, config: config)

    XCTAssertTrue(result.isEmpty)
  }

  func testDisabledTypesAreRemovedButEnabledOnesSurvive() {
    var config = defaultConfig
    config.enabledTypes = [pngType]

    let result = filterContents(
      [dto(stringType, "hi"), dto(pngType, Data([0x89]))],
      application: nil,
      config: config
    )

    XCTAssertEqual(result.map(\.type), [pngType])
  }

  func testIgnoredBuiltInTypeCollapsesToEmpty() {
    // A transient type is in the ignored set; `shouldIgnore(types)` returns true
    // because the type set is not disjoint from ignoredTypes.
    let result = filterContents(
      [dto(stringType, "hi"), dto(transientType, "x")],
      application: nil,
      config: defaultConfig
    )

    XCTAssertTrue(result.isEmpty)
  }

  func testCustomIgnoredTypeCollapsesToEmpty() {
    // Defaults[.ignoredPasteboardTypes] is unioned into ignoredTypes.
    let custom = "org.example.Confidential"
    var config = defaultConfig
    config.ignoredTypes.insert(custom)

    let result = filterContents(
      [dto(stringType, "hi"), dto(custom, "x")],
      application: nil,
      config: config
    )

    XCTAssertTrue(result.isEmpty)
  }

  // MARK: - filteredTypes prefixes (~251-255)

  func testDynamicTypePrefixIsFiltered() {
    let dynType = "dyn.ah62d4qmxhk4d425try1g44pdsm11g55gsu1e82xnqzv"
    let result = filterContents(
      [dto(stringType, "hi"), dto(dynType, "x")],
      application: nil,
      config: defaultConfig
    )

    XCTAssertEqual(result.map(\.type), [stringType])
  }

  func testMicrosoftSourcePrefixIsFiltered() {
    let msType = "com.microsoft.ole.source.someid"
    let result = filterContents(
      [dto(stringType, "hi"), dto(msType, "x")],
      application: nil,
      config: defaultConfig
    )

    XCTAssertEqual(result.map(\.type), [stringType])
  }

  // MARK: - Microsoft link/object/pdf subtraction (~260-262)

  func testMicrosoftLinkAndObjectLinkSubtractPdfAndLinks() {
    // When both com.microsoft.Link-Source and com.microsoft.ObjectLink are present,
    // those two types AND the pdf type are removed (Word bookmark rule).
    let result = filterContents(
      [
        dto(stringType, "hi"),
        dto(microsoftLinkSource, "x"),
        dto(microsoftObjectLink, "y"),
        dto(pdfType, "z")
      ],
      application: nil,
      config: defaultConfig
    )

    XCTAssertEqual(Set(result.map(\.type)), Set([stringType]))
  }

  func testMicrosoftLinkAloneDoesNotSubtract() {
    // The subtraction only triggers when BOTH link-source and object-link present.
    let result = filterContents(
      [dto(stringType, "hi"), dto(microsoftLinkSource, "x"), dto(pdfType, "z")],
      application: nil,
      config: defaultConfig
    )

    XCTAssertEqual(Set(result.map(\.type)), Set([stringType, microsoftLinkSource, pdfType]))
  }

  // MARK: - filteredTypes unsupported-type parity (~251-265)

  func testUnsupportedCustomTypeSurvivesAlongsideEnabledType() {
    // `Clipboard.filteredTypes` removes only DISABLED types (supported − enabled);
    // unsupported/custom UTIs are KEPT for round-trip fidelity. A copy with a
    // standard enabled type plus a custom type keeps BOTH.
    let custom = "org.example.CustomPayload"

    let result = filterContents(
      [dto(stringType, "hi"), dto(custom, "payload")],
      application: nil,
      config: defaultConfig
    )

    XCTAssertEqual(Set(result.map(\.type)), Set([stringType, custom]))
  }

  func testUnsupportedCustomTypeAloneIsDroppedByGlobalGate() {
    // A copy whose only type is unsupported is disjoint from enabledTypes, so
    // `shouldIgnore(types)` collapses it (parity with checkForChangesInPasteboard:185).
    let custom = "org.example.CustomPayload"

    let result = filterContents(
      [dto(custom, "payload")],
      application: nil,
      config: defaultConfig
    )

    XCTAssertTrue(result.isEmpty)
  }

  // MARK: - size cap (contents(from:) ~241-243)

  func testContentOverMaxValueSizeIsDropped() {
    var config = defaultConfig
    config.maxValueSize = 4

    let result = filterContents(
      [dto(stringType, "hello")], // 5 bytes > 4
      application: nil,
      config: config
    )

    XCTAssertTrue(result.isEmpty)
  }

  func testContentExactlyAtMaxValueSizeIsKept() {
    var config = defaultConfig
    config.maxValueSize = 5

    let result = filterContents(
      [dto(stringType, "hello")], // exactly 5 bytes
      application: nil,
      config: config
    )

    XCTAssertEqual(result.map(\.type), [stringType])
  }

  func testOversizedContentDroppedWhileOthersSurvive() {
    var config = defaultConfig
    config.maxValueSize = 2

    let result = filterContents(
      [dto(stringType, "ab"), dto(pngType, Data([0x89, 0x50, 0x4e]))], // png is 3 > 2
      application: nil,
      config: config
    )

    XCTAssertEqual(result.map(\.type), [stringType])
  }

  // MARK: - isEmptyString rule (~312-322, gated by richText ~324-344)

  func testWhitespaceOnlyStringWithNoRichTextCollapsesToEmpty() {
    let result = filterContents(
      [dto(stringType, "   \n")],
      application: nil,
      config: defaultConfig
    )

    XCTAssertTrue(result.isEmpty)
  }

  func testNonEmptyStringSurvives() {
    let result = filterContents(
      [dto(stringType, "x")],
      application: nil,
      config: defaultConfig
    )

    XCTAssertEqual(result.map(\.type), [stringType])
  }

  func testLargeStringIsNotTreatedAsEmptyEvenIfWhitespacePrefix() {
    // isEmptyString returns false once the string exceeds titlePreviewLimit, so a
    // large all-whitespace string is kept.
    var config = defaultConfig
    config.titlePreviewLimit = 3

    let result = filterContents(
      [dto(stringType, String(repeating: " ", count: 10))],
      application: nil,
      config: config
    )

    XCTAssertEqual(result.map(\.type), [stringType])
  }

  // MARK: - richText detection (~324-344)

  func testWhitespaceStringWithNonEmptyRtfSurvives() {
    // A non-empty RTF representation means the copy carries real content even
    // though the plain-text flavor is whitespace.
    let rtf = nonEmptyRTF()
    let result = filterContents(
      [dto(stringType, "  "), dto(rtfType, rtf)],
      application: nil,
      config: defaultConfig
    )

    XCTAssertEqual(Set(result.map(\.type)), Set([stringType, rtfType]))
  }

  func testWhitespaceStringWithEmptyRtfStillCollapses() {
    // An RTF that parses to empty text does NOT save a whitespace string.
    let emptyRtf = emptyRTF()
    let result = filterContents(
      [dto(stringType, "  "), dto(rtfType, emptyRtf)],
      application: nil,
      config: defaultConfig
    )

    XCTAssertTrue(result.isEmpty)
  }

  func testRtfOverRichTextParsingLimitIsTreatedAsRich() {
    // richText(_:) early-returns true when the RTF payload exceeds the parsing
    // limit, so a whitespace string with a huge RTF survives.
    var config = defaultConfig
    config.richTextParsingLimit = 8

    let hugeRtf = Data(repeating: 0x61, count: 16) // 16 bytes > 8 limit
    let result = filterContents(
      [dto(stringType, "  "), dto(rtfType, hugeRtf)],
      application: nil,
      config: config
    )

    XCTAssertEqual(Set(result.map(\.type)), Set([stringType, rtfType]))
  }

  func testWhitespaceStringWithNonEmptyHtmlSurvives() {
    let html = "<html><body>hi</body></html>".data(using: .utf8)!
    let result = filterContents(
      [dto(stringType, "  "), dto(htmlType, html)],
      application: nil,
      config: defaultConfig
    )

    XCTAssertEqual(Set(result.map(\.type)), Set([stringType, htmlType]))
  }

  // MARK: - regex ignore (~283-310)

  func testIgnoreRegexpMatchingStringCollapsesToEmpty() {
    var config = defaultConfig
    config.ignoreRegexp = ["secret"]

    let result = filterContents(
      [dto(stringType, "this is a secret message")],
      application: nil,
      config: config
    )

    XCTAssertTrue(result.isEmpty)
  }

  func testIgnoreRegexpNonMatchingKeepsContent() {
    var config = defaultConfig
    config.ignoreRegexp = ["nomatch"]

    let result = filterContents(
      [dto(stringType, "hello world")],
      application: nil,
      config: config
    )

    XCTAssertEqual(result.map(\.type), [stringType])
  }

  func testUnsafeRegexpIsSkippedAndContentKept() {
    // A pattern with nested quantifiers is rejected by
    // Search.isLikelyUnsafeRegularExpression and skipped, so it does not ignore.
    var config = defaultConfig
    config.ignoreRegexp = ["(a+)+"]

    let result = filterContents(
      [dto(stringType, "aaaa")],
      application: nil,
      config: config
    )

    XCTAssertEqual(result.map(\.type), [stringType])
  }

  func testStringOverRegexpInputLimitSkipsRegex() {
    // shouldIgnore(item) bails when the string data exceeds the input limit, so a
    // huge string is not regex-tested (and here also survives the empty rule).
    var config = defaultConfig
    config.regularExpressionInputLimit = 4
    config.ignoreRegexp = [".*"]

    let result = filterContents(
      [dto(stringType, "abcdefghij")], // 10 bytes > 4 limit
      application: nil,
      config: config
    )

    XCTAssertEqual(result.map(\.type), [stringType])
  }

  // MARK: - application ignore (shouldIgnore(sourceAppBundle:) ~275-281)

  func testIgnoredApplicationCollapsesToEmpty() {
    var config = defaultConfig
    config.ignoredApps = ["org.example.Blocked"]

    let result = filterContents(
      [dto(stringType, "hi")],
      application: "org.example.Blocked",
      config: config
    )

    XCTAssertTrue(result.isEmpty)
  }

  func testApplicationNotIgnoredSurvives() {
    var config = defaultConfig
    config.ignoredApps = ["org.example.Blocked"]

    let result = filterContents(
      [dto(stringType, "hi")],
      application: "org.example.Allowed",
      config: config
    )

    XCTAssertEqual(result.map(\.type), [stringType])
  }

  func testIgnoreAllAppsExceptListedBlocksUnlisted() {
    var config = defaultConfig
    config.ignoreAllAppsExceptListed = true
    config.ignoredApps = ["org.example.Allowed"]

    let blocked = filterContents(
      [dto(stringType, "hi")],
      application: "org.example.Unlisted",
      config: config
    )
    XCTAssertTrue(blocked.isEmpty)

    let allowed = filterContents(
      [dto(stringType, "hi")],
      application: "org.example.Allowed",
      config: config
    )
    XCTAssertEqual(allowed.map(\.type), [stringType])
  }

  func testNilApplicationNeverIgnored() {
    // When the source app is unknown, app-ignore does not fire.
    var config = defaultConfig
    config.ignoredApps = ["org.example.Blocked"]

    let result = filterContents(
      [dto(stringType, "hi")],
      application: nil,
      config: config
    )

    XCTAssertEqual(result.map(\.type), [stringType])
  }

  // MARK: - isEffectivelyEmpty (helper, parity with ~312-322)

  func testIsEffectivelyEmptyTrueForWhitespaceStringWithoutRichText() {
    XCTAssertTrue(isEffectivelyEmpty(
      [dto(stringType, " \n")],
      richTextPresent: false,
      titlePreviewLimit: 1_000
    ))
  }

  func testIsEffectivelyEmptyFalseWhenRichTextPresent() {
    XCTAssertFalse(isEffectivelyEmpty(
      [dto(stringType, " ")],
      richTextPresent: true,
      titlePreviewLimit: 1_000
    ))
  }

  func testIsEffectivelyEmptyFalseWhenNoStringContent() {
    XCTAssertFalse(isEffectivelyEmpty(
      [dto(pngType, Data([0x89]))],
      richTextPresent: false,
      titlePreviewLimit: 1_000
    ))
  }

  // MARK: - Sendable sanity

  func testIngestConfigIsSendable() {
    requireSendable(IngestConfig.self)
  }

  private func requireSendable<T: Sendable>(_ type: T.Type) {}

  // MARK: - RTF helpers

  /// Builds a real RTF document whose attributed string is "x" (non-empty).
  private func nonEmptyRTF() -> Data {
    NSAttributedString(string: "x").rtf(
      from: NSRange(location: 0, length: 1),
      documentAttributes: [:]
    ) ?? "{\\rtf1 x}".data(using: .utf8)!
  }

  /// Builds an RTF document whose attributed string parses to an empty string.
  private func emptyRTF() -> Data {
    NSAttributedString(string: "").rtf(
      from: NSRange(location: 0, length: 0),
      documentAttributes: [:]
    ) ?? "{\\rtf1}".data(using: .utf8)!
  }
}
