import Defaults
import Foundation

#if os(macOS)
import AppKit
public typealias PasteboardType = NSPasteboard.PasteboardType
#else
import UIKit
import UniformTypeIdentifiers

public struct PasteboardType: Hashable, RawRepresentable, Sendable {
  public let rawValue: String
  public init(rawValue: String) { self.rawValue = rawValue }
  public init(_ rawValue: String) { self.rawValue = rawValue }
}

extension PasteboardType: Defaults.Serializable {}

extension PasteboardType {
  // Standard types mapped to UTType identifiers
  static let string = PasteboardType(rawValue: UTType.plainText.identifier)
  static let html = PasteboardType(rawValue: UTType.html.identifier)
  static let rtf = PasteboardType(rawValue: UTType.rtf.identifier)
  static let tiff = PasteboardType(rawValue: UTType.tiff.identifier)
  static let png = PasteboardType(rawValue: UTType.png.identifier)
  static let fileURL = PasteboardType(rawValue: UTType.fileURL.identifier)
}
#endif

// Common extension for both platforms - custom Maccy types
extension PasteboardType {
  static let heic = PasteboardType(rawValue: "public.heic")
  static let jpeg = PasteboardType(rawValue: "public.jpeg")
  static let universalClipboard = PasteboardType(rawValue: "com.apple.is-remote-clipboard")

  // See http://nspasteboard.org for more details.
  static let autoGenerated = PasteboardType(rawValue: "org.nspasteboard.AutoGeneratedType")
  static let concealed = PasteboardType(rawValue: "org.nspasteboard.ConcealedType")
  static let source = PasteboardType(rawValue: "org.nspasteboard.source")
  static let transient = PasteboardType(rawValue: "org.nspasteboard.TransientType")

  // https://github.com/p0deje/Maccy/issues/429#issuecomment-1182575226
  static let modified = PasteboardType(rawValue: "x.nspasteboard.ModifiedType")

  // Marks that copy was made from Maccy.
  static let fromMaccy = PasteboardType(rawValue: "org.p0deje.Maccy")

  // Types that indicate Microsoft Word bookmarks (links).
  static let microsoftObjectLink = PasteboardType(rawValue: "com.microsoft.ObjectLink")
  static let microsoftLinkSource = PasteboardType(rawValue: "com.microsoft.Link-Source")

  // Safari preview and extra metadata that changes frequently.
  static let linkPresentationMetadata = PasteboardType(rawValue: "com.apple.linkpresentation.metadata")
  static let customWebKitPasteboardData = PasteboardType(rawValue: "com.apple.WebKit.custom-pasteboard-data")

  // Chromium (VSCode)
  static let customChromiumWebData = PasteboardType(rawValue: "org.chromium.web-custom-data")
  static let chromiumSourceUrl = PasteboardType(rawValue: "org.chromium.source-url")
  static let chromiumSourceToken = PasteboardType(rawValue: "org.chromium.internal.source-rfh-token")

  // Apple Notes
  static let notesRichText = PasteboardType(rawValue: "com.apple.notes.richtext")
}
