import AppKit
import Foundation

/// Injectable, value-type snapshot of the configuration the ingest filter needs.
///
/// `Clipboard` reads its filtering knobs live from `Defaults[...]` and from
/// private constants inside `Clipboard.contents(from:)` / `filteredTypes` /
/// `shouldIgnore(...)`. That coupling makes the rules impossible to exercise
/// off-main or with synthetic data. `IngestConfig` captures the exact same knobs
/// as plain values so that `filterContents(_:application:config:)` is a pure,
/// `Sendable`-safe function with no `Defaults` reads — the background ingest
/// actor (BS-2.2b) builds one of these on the main thread and hands it across.
///
/// Every field has a 1:1 counterpart in `Clipboard.swift`; the doc comments name
/// the line so the parity stays auditable as `Clipboard` evolves.
struct IngestConfig: Sendable, Equatable {
  /// RawValues of `Clipboard.supportedTypes` (~Clipboard.swift:24-33):
  /// `.fileURL, .heic, .html, .jpeg, .png, .rtf, .string, .tiff`.
  var supportedTypes: Set<String>

  /// RawValues of `Defaults[.enabledPasteboardTypes]`. Used both to drop disabled
  /// types (`filteredTypes`, ~251-265) and as the "is anything we care about
  /// enabled" gate in `shouldIgnore(types)` (~271).
  var enabledTypes: Set<String>

  /// The ignored type set = `Clipboard.ignoredTypes` (~34-38:
  /// `.autoGenerated, .concealed, .transient`) UNION `Defaults[.ignoredPasteboardTypes]`,
  /// as rawValues. Mirrors `shouldIgnore(types)` (~268-269).
  var ignoredTypes: Set<String>

  /// Mirrors `HistoryItemContent.maxValueSize`. A content whose `value.count`
  /// exceeds this is dropped (`contents(from:)` ~241-243).
  var maxValueSize: Int

  /// `512 * 1024`, matching `Clipboard.richTextParsingLimit` (~11) and
  /// `HistoryItem.richTextParsingLimit`. RTF/HTML larger than this is treated as
  /// "rich text present" without parsing (`richText(_:)` ~326, ~335).
  var richTextParsingLimit: Int

  /// `2_000`, matching `Clipboard.regularExpressionInputLimit` (~10). Strings
  /// longer than this are not regex-tested (`shouldIgnore(item)` ~285-286).
  var regularExpressionInputLimit: Int

  /// `Defaults[.ignoreRegexp]`. Each safe pattern is matched against the `.string`
  /// content; a match discards the whole batch (`shouldIgnore(item)` ~290-308).
  var ignoreRegexp: [String]

  /// `Defaults[.ignoredApps]`. App bundle ids to ignore or (when
  /// `ignoreAllAppsExceptListed` is true) to allow.
  var ignoredApps: [String]

  /// `Defaults[.ignoreAllAppsExceptListed]`. When true the semantics of
  /// `ignoredApps` flip from "block list" to "allow list"
  /// (`shouldIgnore(sourceAppBundle:)` ~275-281).
  var ignoreAllAppsExceptListed: Bool

  /// `HistoryItem.titlePreviewLimit` (1_000). The empty-string rule only fires
  /// when the `.string` payload is at most this large (`isEmptyString` ~316).
  var titlePreviewLimit: Int
}

/// Pure ingest decision: applies the `Clipboard` filtering/ignore rules to an
/// already-materialized, flat `[ContentDTO]`.
///
/// This is the off-main, DB-free, `NSPasteboard`-free twin of the per-item work
/// in `Clipboard.checkForChangesInPasteboard` (~158-223) and
/// `Clipboard.contents(from:)` (~227-247). Because `Clipboard` merges every
/// pasteboard item's contents into a single record before storing (the
/// BBEdit/Edge 2-items case, ~193-200), this function receives an already-flat
/// array and applies the rules once to the whole batch — preserving the
/// "merge all data into a single record" intent.
///
/// Rules applied, in the same order `Clipboard` applies them:
///
/// 1. **Application ignore** — `shouldIgnore(sourceAppBundle:)` (~275-281).
///    If `application` matches the configured app list (allow- or block-list
///    depending on `ignoreAllAppsExceptListed`), returns `[]`. A nil
///    `application` is never ignored (Clipboard only checks when the frontmost
///    app's bundle id is known, ~189).
///
/// 2. **Global type gate** — `shouldIgnore(types)` (~267-273). Computed over the
///    union of all `ContentDTO.type` values. Returns `[]` if that set is disjoint
///    from `enabledTypes` (nothing we care about) OR not disjoint from
///    `ignoredTypes` (a transient/concealed/auto-generated/custom-ignored marker).
///
/// 3. **Empty-string rule** — `isEmptyString` (~312-322) gated by `richText`
///    (~324-344). If a `.string` content is present and trims to whitespace
///    (within `titlePreviewLimit`) AND there is no non-empty RTF/HTML
///    representation, returns `[]`.
///
/// 4. **Regex ignore** — `shouldIgnore(item)` (~283-310). If the `.string`
///    content (when ≤ `regularExpressionInputLimit`) matches any safe
///    `ignoreRegexp` entry, returns `[]`. Unsafe patterns
///    (`Search.isLikelyUnsafeRegularExpression`) are skipped.
///
/// 5. **Type filtering** — `filteredTypes` (~251-265). Drops types not in
///    `supportedTypes ∩ enabledTypes` (disabled types), drops `dyn.`-prefixed
///    (~254) and `com.microsoft.ole.source.`-prefixed (~255) types, and applies
///    the Microsoft Word bookmark subtraction (~260-262): when both
///    `com.microsoft.Link-Source` and `com.microsoft.ObjectLink` are present,
///    those two types plus `com.adobe.pdf` are removed.
///
/// 6. **Size cap** — `contents(from:)` (~241-243). Any remaining content whose
///    `value?.count` exceeds `maxValueSize` is dropped.
///
/// The function is pure: it reads no globals, mutates nothing, and touches only
/// the value types it is given. `NSAttributedString(rtf:)/(html:)` is invoked
/// for rich-text detection (mirroring `richText(_:)`); under the project's
/// `SWIFT_STRICT_CONCURRENCY=minimal` setting this compiles cleanly on a
/// background actor. The pure empty-string predicate itself is also exposed as
/// `isEffectivelyEmpty(_:richTextPresent:titlePreviewLimit:)` so the decision
/// can be unit-tested without `NSAttributedString`.
///
/// - Parameters:
///   - raw: The flat, already-merged contents to filter. Order is preserved for
///     surviving contents.
///   - application: Source app bundle id of the copy, or nil if unknown.
///   - config: The configuration snapshot.
/// - Returns: The surviving contents in their original order, or `[]` if any
///   gate rules out the whole batch.
func filterContents(
  _ raw: [ContentDTO],
  application: String?,
  config: IngestConfig
) -> [ContentDTO] {
  if shouldIgnoreApplication(application, config: config) {
    return []
  }

  let typeSet = Set(raw.map(\.type))
  if shouldIgnoreTypes(typeSet, config: config) {
    return []
  }

  // Empty-string rule: only meaningful when a `.string` content is present
  // (Clipboard.isEmptyString returns false without one). isEffectivelyEmpty
  // re-checks that presence internally, so no separate guard is needed.
  let stringContent = raw.first { $0.type == NSPasteboard.PasteboardType.string.rawValue }
  if isEffectivelyEmpty(
    raw,
    richTextPresent: richTextPresent(in: raw, config: config),
    titlePreviewLimit: config.titlePreviewLimit
  ) {
    return []
  }

  if let stringContent, shouldIgnoreByRegexp(stringContent, config: config) {
    return []
  }

  return raw.filter { content in
    filteredTypeSet(typeSet, config: config).contains(content.type)
      && (content.value?.count ?? 0) <= config.maxValueSize
  }
}

/// Pure predicate for the empty-string rule (~Clipboard.swift:312-322).
///
/// Returns true only when:
/// - a `.string`-typed content is present,
/// - its payload is at most `titlePreviewLimit` bytes,
/// - and that payload trims to an empty string (whitespace/newlines only),
/// - and no rich-text representation is present (`richTextPresent == false`,
///   matching the `!richText(item)` guard in `contents(from:)` ~229).
///
/// Factored out so the decision can be unit-tested without `NSAttributedString`.
func isEffectivelyEmpty(
  _ contents: [ContentDTO],
  richTextPresent: Bool,
  titlePreviewLimit: Int
) -> Bool {
  guard !richTextPresent else { return false }
  guard let stringContent = contents.first(where: {
    $0.type == NSPasteboard.PasteboardType.string.rawValue
  }) else {
    return false
  }

  guard let data = stringContent.value, data.count <= titlePreviewLimit else {
    return false
  }

  return data.stringPrefix(maxBytes: titlePreviewLimit)?
    .trimmingCharacters(in: .whitespacesAndNewlines).isEmpty == true
}

// MARK: - Rule helpers

/// `shouldIgnore(sourceAppBundle:)` (~Clipboard.swift:275-281). A nil bundle id
/// is never ignored (the caller checks `sourceApp?.bundleIdentifier` first ~189).
private func shouldIgnoreApplication(_ application: String?, config: IngestConfig) -> Bool {
  guard let application else { return false }
  if config.ignoreAllAppsExceptListed {
    return !config.ignoredApps.contains(application)
  }
  return config.ignoredApps.contains(application)
}

/// `shouldIgnore(types)` (~Clipboard.swift:267-273). True when the type set is
/// disjoint from enabled types OR not disjoint from ignored types.
private func shouldIgnoreTypes(_ types: Set<String>, config: IngestConfig) -> Bool {
  types.isDisjoint(with: config.enabledTypes) ||
    !types.isDisjoint(with: config.ignoredTypes)
}

/// `richText(_:)` (~Clipboard.swift:324-344) collapsed to a boolean.
///
/// Returns true when an RTF or HTML content exists and either exceeds
/// `richTextParsingLimit` (early-return-true path, ~326/~335) or parses to a
/// non-empty attributed string.
private func richTextPresent(in contents: [ContentDTO], config: IngestConfig) -> Bool {
  let rtf = contents.first { $0.type == NSPasteboard.PasteboardType.rtf.rawValue }?.value
  if let rtf {
    guard rtf.count <= config.richTextParsingLimit else { return true }
    if let attributed = NSAttributedString(rtf: rtf, documentAttributes: nil) {
      return !attributed.string.isEmpty
    }
  }

  let html = contents.first { $0.type == NSPasteboard.PasteboardType.html.rawValue }?.value
  if let html {
    guard html.count <= config.richTextParsingLimit else { return true }
    if let attributed = NSAttributedString(html: html, documentAttributes: nil) {
      return !attributed.string.isEmpty
    }
  }

  return false
}

/// `shouldIgnore(item)` regex half (~Clipboard.swift:283-310). True when the
/// string content (≤ `regularExpressionInputLimit`) matches any safe
/// `ignoreRegexp` pattern. Unsafe patterns are skipped; uncompilable patterns
/// are skipped. Regexes are recompiled on each call — correct, if slower than
/// `Clipboard`'s cached map.
private func shouldIgnoreByRegexp(_ stringContent: ContentDTO, config: IngestConfig) -> Bool {
  guard let data = stringContent.value,
        data.count <= config.regularExpressionInputLimit,
        let string = data.stringPrefix(maxBytes: config.regularExpressionInputLimit) else {
    return false
  }

  let range = NSRange(string.startIndex..., in: string)
  for pattern in config.ignoreRegexp {
    guard !Search.isLikelyUnsafeRegularExpression(pattern) else { continue }
    guard let regex = try? NSRegularExpression(pattern: pattern) else { continue }
    if regex.numberOfMatches(in: string, range: range) > 0 {
      return true
    }
  }
  return false
}

/// `filteredTypes` (~Clipboard.swift:251-265). Computes the surviving type set.
///
/// `Clipboard.filteredTypes` removes only DISABLED types
/// (`disabledTypes = supportedTypes − enabledTypes`): a type is dropped iff it
/// is supported but not enabled. Types that are NOT in `supportedTypes` at all
/// (custom / app-specific UTIs) are KEPT — Maccy captures them for round-trip
/// fidelity. So this mirrors `types.subtracting(disabled)`, NOT an intersection
/// with `supportedTypes ∩ enabledTypes` (which would wrongly drop custom types).
/// Then it drops the `dyn.` and `com.microsoft.ole.source.` prefixes and applies
/// the Microsoft Word bookmark subtraction.
private func filteredTypeSet(_ types: Set<String>, config: IngestConfig) -> Set<String> {
  let dynamicTypePrefix = "dyn."
  let microsoftSourcePrefix = "com.microsoft.ole.source."
  let microsoftLinkSource = "com.microsoft.Link-Source"
  let microsoftObjectLink = "com.microsoft.ObjectLink"
  let pdf = "com.adobe.pdf"

  let disabled = config.supportedTypes.subtracting(config.enabledTypes)
  var result = types
    .subtracting(disabled)
    .filter { !$0.hasPrefix(dynamicTypePrefix) }
    .filter { !$0.hasPrefix(microsoftSourcePrefix) }

  if result.isSuperset(of: [microsoftLinkSource, microsoftObjectLink]) {
    result.subtract([microsoftLinkSource, microsoftObjectLink, pdf])
  }

  return result
}
